name: Tests GPU

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["self-hosted"]
#        python-version: ["3.7", "3.8", "3.9"]
        python-version: ["3.7"]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
      PARALLEL: "true"
      COVERAGE: "true"

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needed by codecov.io

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          channels: conda-forge,rapidsai
          channel-priority: true
          python-version: ${{ matrix.python-version }}
          environment-file: continuous_integration/environment-${{ matrix.python-version }}-gpu.yaml
          activate-environment: test-environment
          auto-activate-base: false

      - name: Hack around https://github.com/dask/dask/issues/7189
        shell: bash -l {0}
        if: ${{ matrix.os == 'macos-latest' && matrix.python-version == '3.8' }}
        run: |
          # FIXME https://github.com/mamba-org/mamba/issues/412
          # mamba uninstall --force numpy
          conda uninstall --force numpy
          python -m pip install --no-deps numpy==1.20

      - name: Hack around https://github.com/ipython/ipython/issues/12197
        # This upstream issue causes an interpreter crash when running
        # test_base.py::test_tokenize_object_with_recursion_error_returns_uuid
        shell: bash -l {0}
        if: ${{ matrix.os == 'windows-latest' && matrix.python-version == '3.9' }}
        run: mamba uninstall ipython

      - name: Install
        shell: bash -l {0}
        run: source continuous_integration/scripts/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: source continuous_integration/scripts/run_tests.sh

      - name: Coverage
        uses: codecov/codecov-action@v1
